export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Disposable Face Masks - Packs',
        description: 'Ultimate Masks that are made of Premium quality Material HELPS in protecting cross infection and providing the user excellent protection from the finest particulates.Pleated Design for additional comfort to the user. 3ply Blue Colour .Packed securely in Mailing Bag! Next day delivery option available.',
        publishDate: '11.05.2020',
        updateDate: '15.05.2020',
        mail: 'medical@example.com',
        status: 'published',
        sellingState: 'new',
        location: 'London',
        shipping: 'after payment',
        image: 'https://images.pexels.com/photos/3786126/pexels-photo-3786126.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
        price: 0.99,
        userId: '1',
      },
      {
        id: '2',
        title: 'Cute Ragdoll kittens male and female',
        description: 'Boy and girl available. Health checked, vaccinated, wormed and micro chipped. They were raised indoors/outdoors and are used to children and other dogs. They have a lovely playful character and will be a great addition to any family.',
        publishDate: '13.05.2020',
        updateDate: '14.05.2020',
        mail: 'mycutecats@example.com',
        status: 'published',
        sellingState: 'used',
        location: 'Liverpool',
        shipping: 'only cash on delivery',
        image: 'https://images.pexels.com/photos/4012470/pexels-photo-4012470.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 200,
        userId: '2',
      },
      {
        id: '3',
        title: 'red shoes',
        description: 'Shoes. Ladies strap open toe shoes. Colour: Red. Size: 9. Price: £5. Delivery:£3',
        publishDate: '10.05.2020',
        updateDate: '12.05.2020',
        mail: 'medical@example.com',
        status: 'published',
        sellingState: 'new',
        location: 'London',
        shipping: 'after payment',
        image: 'https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 5,
        userId: '1',
      },
      {
        id: '4',
        title: 'Natural SNAIL anti-aging EYE CREAM',
        description: 'Orientana almost 99% Natural SNAIL anti-aging EYE CREAM for under eyes puffiness & bags, dark circles, dry skin, 15 ml',
        publishDate: '11.05.2020',
        updateDate: '15.05.2020',
        mail: 'snailcream@example.com',
        status: 'published',
        sellingState: 'broken',
        location: 'London',
        shipping: 'all options possible',
        image: 'https://images.pexels.com/photos/725998/pexels-photo-725998.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 13,
        userId: '3',
      },
      {
        id: '5',
        title: 'Secondary Teacher - Music Piano',
        description: 'Teacher of Music needed for a lovely school in Barnet! Majority KS3 music teaching but need to be able to deliver the coursework components of the Edexcel GCSE Music to two small class of GCSE - 6 periods a week.',
        publishDate: '17.05.2020',
        updateDate: '20.05.2020',
        mail: 'musicteacher@example.com',
        status: 'published',
        sellingState: 'other',
        location: 'Glasgow',
        shipping: '',
        image: 'https://images.pexels.com/photos/4038337/pexels-photo-4038337.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 0,
        userId: '4',
      },
      {
        id: '6',
        title: 'Two 2 seater sofas ',
        description: 'Two 2 seater cream fabric sofas, good condition. Collect only..',
        publishDate: '13.05.2020',
        updateDate: '16.05.2020',
        mail: 'kate@example.com',
        status: 'published',
        sellingState: 'used',
        location: 'London',
        shipping: 'after payment',
        image: 'https://images.pexels.com/photos/3754310/pexels-photo-3754310.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 40,
        userId: '5',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    rights: '',
    //authenticated: false,
    authenticated: true,
  },
};
